Repository IEEE-VIT/Haunted_House, pull requests merged in 2023-09, with the labels that each got.

#25 Issue17
  npcs_actions.py
Labels: easy

#28 a new npc queen has been added
  npcs.py
Labels: easy

#35 added quit game function
  game.py
Labels: medium

#32 Feature Added: LookAround
  game.py
Labels: medium

#34 Updated README.md
  README.md
Labels: easy

#40 Function Sorcerer_Challenge
  npcs_actions.py
Labels: medium

#45 inventory_status
  game.py
Labels: easy

#46 Updated README.md with layout
  House-Layout.png
  README.md
Labels: easy

#51 FeatureAdded:HandleRats
  game.py
Labels: hard

#67 added user inout
  game.py
Labels: hard

#70 layout_of_the_house.md
  README.md
Labels: easy

#71 Update npcs_actions.py
  npcs_actions.py
Labels: medium

#80 Update leaderboard.py
  leaderboard.py
Labels: medium

#72 Update game.py for unlock() function
  game.py
Labels: medium

#84 FeatureAdded:TakeItem
  game.py
Labels: medium

#86 Update leaderboard.py
  leaderboard.py
Labels: easy

#89 added handel_user_command()
  game.py
Labels: medium

#97 sFunction is added
  game.py
  leaderboard.py
Labels: hard

#95 Update npcs_actions.py
  npcs_actions.py
Labels: medium

#101 Feature Added: TalkTo
  game.py
Labels: hard

#100 updateFunction is added
  game.py
  leaderboard.py
Labels: medium
